---
- name: Reset hosts
  hosts: all
  tasks:
    - name: uninstall packages
      yum: 
        name: 
          - httpd
          - firewalld
        state: absent
        
    - name: remove file
      file:
        dest: /var/www/html/index.html
        state: absent
        
